// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CabinetDetail defines model for CabinetDetail.
type CabinetDetail struct {
	Drawers *[]DrawerDetail `json:"drawers,omitempty"`
	Id      *UUID           `json:"id,omitempty"`
	Name    *string         `json:"name,omitempty"`
}

// CabinetList defines model for CabinetList.
type CabinetList struct {
	Items      *[]CabinetSummary `json:"items,omitempty"`
	NextCursor *UUID             `json:"nextCursor,omitempty"`
}

// CabinetSummary defines model for CabinetSummary.
type CabinetSummary struct {
	Id   *UUID   `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// DrawerDetail defines model for DrawerDetail.
type DrawerDetail = DrawerSummary

// DrawerSummary defines model for DrawerSummary.
type DrawerSummary struct {
	Id    *UUID   `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
}

// ServerStatus defines model for ServerStatus.
type ServerStatus struct {
	Status *string `json:"status,omitempty"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// CabinetsListParams defines parameters for CabinetsList.
type CabinetsListParams struct {
	// Cursor Cursor used for paginated responses
	Cursor *UUID `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cabinets
	// (GET /cabinets)
	CabinetsList(c *gin.Context, params CabinetsListParams)
	// Get cabinet and contents
	// (GET /cabinets/{cabinetId})
	CabinetGet(c *gin.Context, cabinetId UUID)

	// (GET /status)
	StatusGet(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CabinetsList operation middleware
func (siw *ServerInterfaceWrapper) CabinetsList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CabinetsListParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CabinetsList(c, params)
}

// CabinetGet operation middleware
func (siw *ServerInterfaceWrapper) CabinetGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "cabinetId" -------------
	var cabinetId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cabinetId", c.Param("cabinetId"), &cabinetId, runtime.BindStyledParameterOptions{Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cabinetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CabinetGet(c, cabinetId)
}

// StatusGet operation middleware
func (siw *ServerInterfaceWrapper) StatusGet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StatusGet(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/cabinets", wrapper.CabinetsList)
	router.GET(options.BaseURL+"/cabinets/:cabinetId", wrapper.CabinetGet)
	router.GET(options.BaseURL+"/status", wrapper.StatusGet)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RWXY+bOhD9K9bcfWQTslld3ctblairSFu1UrRPq1RyYABvwaa22d0U8d8rG0NCIF0q",
	"9ePNNuMzZ2bODK4gFHkhOHKtIKhAhSnm1C5XdM846jVqyjJzQLPsYwzBYwVXEmMI4J/58fLc3Zy7a9sy",
	"z6k8QO1VUEhRoNQMLW4k6QtKu2Qac7v4EeDa2jsatQf6UCAEQKWkB6iPB2L/hKGGejc48dpY7pnSxl2f",
	"UMdiEp1BfGeEPOD4qlelVEK+hfXwsFmPhdARbr0MOUfTsD3gNEdj61woLRlPxp32Mj254M2tLh+7i8C/",
	"IJiM7jGbGM0W5TPKraa6VEOfqjsPBTeqAPEFvCm4lktQQSxkTs3FsmQReJDT13vkiU4hWP7rQc746bag",
	"WqPkEMDnR//6f3od76r/6utufTthvbipr0Y41h4wHgubFqYz823VpZCsqaZ7qhA8eEapmDAc/Nli5ptg",
	"RIGcFgwCWM782RIs0dTmZR42GrSbBG3jRKhCyQrdoJh2Iq0VeWE6JQVNGKf2uwWXdr2JDCdnaJvQ+JE0",
	"R20nweM5ctM+pFQYkVjIFhYjIlEVgitUYKKGAL6WKA/Q6hzCpvE8N8mmduA5gQ/0leVlTniZ71ESERM7",
	"HIgWRKIuJb/gPmM50z3vEca0zDQEC9+3IjG47Y5xt+uqyrjGBCXUppGOwQYV3Pi+k6tGbqtBiyJjoc3w",
	"/EkZ3tXEsE/noRVQP/ptGYaoVFxmpKuhUcutvxiq4IHTUqdCsm8YNUbLodF7IfcsipDbnlLtJOhLyGib",
	"JkYP4I5gZ8w7Jc4rt9pE9UVV3qEmLknKFI4SxXiSYevmkjDv8E1ZbtYG0OEMtWBa50SJLdWfFeMfKHz7",
	"N/2bpbd1cqmkPOpqdlEFx5Ht6t4vYzPpmyr+tvz1fipj6bPfCVMkRZrp1L1QXDwugl19cjgYfe08TUUW",
	"MZ4Q916yyju+1c5lBsMZth67SDIR2kFqxjXjp73nABt/I3irMe/t2Yj9u08b4iLu7N2+3tXfAwAA////",
	"gAulegoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
