// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CabinetDetail defines model for CabinetDetail.
type CabinetDetail struct {
	Drawers *[]DrawerDetail `json:"drawers,omitempty"`
	Id      *string         `json:"id,omitempty"`
}

// CabinetList defines model for CabinetList.
type CabinetList struct {
	Items      *[]CabinetSummary `json:"items,omitempty"`
	NextCursor *string           `json:"nextCursor,omitempty"`
}

// CabinetSummary defines model for CabinetSummary.
type CabinetSummary struct {
	Id *string `json:"id,omitempty"`
}

// DrawerDetail defines model for DrawerDetail.
type DrawerDetail = DrawerSummary

// DrawerSummary defines model for DrawerSummary.
type DrawerSummary struct {
	Id    *string `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
}

// ServerStatus defines model for ServerStatus.
type ServerStatus struct {
	Status *string `json:"status,omitempty"`
}

// UUID defines model for UUID.
type UUID = string

// CabinetsListParams defines parameters for CabinetsList.
type CabinetsListParams struct {
	// Cursor Cursor used for paginated responses
	Cursor *UUID `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cabinets
	// (GET /cabinets)
	CabinetsList(c *gin.Context, params CabinetsListParams)
	// Get cabinet and contents
	// (GET /cabinets/{cabinetId})
	CabinetGet(c *gin.Context, cabinetId UUID)

	// (GET /status)
	StatusGet(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CabinetsList operation middleware
func (siw *ServerInterfaceWrapper) CabinetsList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CabinetsListParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CabinetsList(c, params)
}

// CabinetGet operation middleware
func (siw *ServerInterfaceWrapper) CabinetGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "cabinetId" -------------
	var cabinetId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cabinetId", c.Param("cabinetId"), &cabinetId, runtime.BindStyledParameterOptions{Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cabinetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CabinetGet(c, cabinetId)
}

// StatusGet operation middleware
func (siw *ServerInterfaceWrapper) StatusGet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StatusGet(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/cabinets", wrapper.CabinetsList)
	router.GET(options.BaseURL+"/cabinets/:cabinetId", wrapper.CabinetGet)
	router.GET(options.BaseURL+"/status", wrapper.StatusGet)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWUW+bMBD+K9atjzRJm2raeJsSrYpUaZOiPlWZdIFLcAc2s03bDPHfJxtDQiEre5i2",
	"N2PO33133+eDEiKZ5VKQMBrCEnSUUIZuucAtF2SWZJCndgPT9MsOwocSLhTtIIR30+PhqT859cfWRZah",
	"OkAVlJArmZMynBxurPCZlFtyQ5lb/A5w6eI9jSoAc8gJQkCl8ADVcUNuHykyUG16O0FTyx3XxqbrEmpZ",
	"jKLTq+8VoQAEvZhFobRUFsu/1UZxsR/i27JrIPsE45FAnVaNVqw+1Ra0OQv8ZwQDSHFL6Ujqa1JPpNYG",
	"TaH7CXS7H0lhNQT5HYIxuPf3q6U9l+HLHYm9SSCcvw8g4+L0MUdjSAkI4dvD7PIjXu425Yfqsl3fjFhf",
	"XVcXA5yqALjYSdcGblL7btFqwJZocIuaIIAnUppLy2E2uZrMLHmZk8CcQwjzyWwyB0c0cX2YRrVp3MOe",
	"nK1j0pHiualRrNlZE8WeuUlYjnsu0L134MqtV7Hl5APdFbF5FGZk3D19eI1cm5sVmmK2k6qBpZgp0rkU",
	"mjTYqiGEHwWpAwQgMLOVR/W1CPyceeuuOfEq68gjcFjC9WzmrWBIuMoxz1MeuWqmj9qSLEemOJ0MTqxu",
	"qesiikjrXZGytl9WmZvZVb/j9wILk0jFf1JcB837QZ+l2vI4JuH8qpsr1ZXL+gj3tvfgt2Bjw1vVp6Vf",
	"reLqrANuyTDfJM3kjiHTXOxTatKcM8EtvWmB1dICehxmJFNkCiUa2a1NT1RvqP6HwjfflX8pvdPJtxJF",
	"3Gp21gXHceh178pYT9Faxb/Wv87AHmqfe8+4ZglhahL/rfb1+Ao21clmb8w0syuRaczFnvk/B+e841/L",
	"a5u5X44u0nLoIEtl5IaWHY1cnN49D1jnG8BbDGVv9gbiP31dMV9xG++fq031KwAA//8e/tdrhAkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
