openapi: 3.0.3
info:
  title: Components Database
  version: 0.1.0
tags:
  - name: cabinet
    description: Cabinets holding drawers of components
  - name: drawer
    description: Drawers of components located within cabinets
  - name: component
    description: Components
paths:
  /cabinets:
    get:
      tags:
        - cabinet
      summary: List cabinets
      description: List cabinets with pagination
      operationId: cabinetsList
      responses:
        '200':
          description: Successful operation
          parameters:
            - name: cursor
              in: query
              description: Cursor used for paginated responses
              required: false
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CabinetList"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    CabinetSummary:
      type: object
      properties:
        id:
          type: string
          nullable: false
    CabinetList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/CabinetSummary"
        nextCursor:
          type: string
          nullable: true
          optional: true
