//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Cabinets struct {
	ID        int64 `sql:"primary_key" fake:"skip"`
	UUID      uuid.UUID
	Name      string
	CreatedAt time.Time  `fake:"skip"`
	UpdatedAt *time.Time `fake:"skip"`
}
