// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

const TableNameCabinet = "cabinets"

// Cabinet mapped from table <cabinets>
type Cabinet struct {
	ID        int64      `gorm:"column:id;type:bigint;not null" json:"id" fake:"skip"`
	UUID      uuid.UUID  `gorm:"column:uuid;type:uuid;not null;index:idx_cabinets_uuid,priority:1;default:gen_random_uuid()" json:"uuid" fake:"skip"`
	Name      string     `gorm:"column:name;type:text;not null" json:"name"`
	CreatedAt time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at" fake:"skip"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at" fake:"skip"`
}

// TableName Cabinet's table name
func (*Cabinet) TableName() string {
	return TableNameCabinet
}
