name: backend test suite

on:
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: backend/go.sum
      - name: Run unit tests
        run: cd backend/ && go test ./...
