name: Tests

on:
  - push

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: |
            backend/go.sum
            cmd/go.sum
      - uses: ./.github/actions/pre-commit
  backend-test:
    name: Run backend test suite
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: |
            backend/go.sum
            cmd/go.sum
      - name: Run backend test suite
        run: |
          go clean -testcache
          task backend-test-local
        env:
          TESTING_DATABASE_DSN: postgresql://test-user:test-pass@localhost:${{ job.services.testdb.ports['5432'] }}/test?sslmode=disable
    services:
      testdb:
        image: postgres:16
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test-user
          POSTGRES_PASSWORD: test-pass
        options: >-
          --health-cmd="pg_isready --dbname=postgresql://test-user:test-pass@localhost:5432/test"
          --health-interval=1s
          --health-timeout=5s
          --health-retries=10
          --health-start-period=120s
        ports:
          - 5432/tcp
  backend-build:
    name: Build backend docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          target: backend
          tags: backend:${{ github.sha }}
