name: Tests

on:
  - push

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: |
            backend/go.sum
            cmd/go.sum
      - uses: ./.github/actions/pre-commit
  backend-test:
    name: Run backend test suite
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - name: Run backend test suite
        run: task backend-test
  backend-build:
    name: Build backend docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          target: backend
          tags: backend:${{ github.sha }}
